---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

There are certain things as, a spider, a ghost, 

The income tax, gout, an umbrella for three 

That I hate, but the thing that I hate the most 

Is a thing they call the Sea.  

Pour some salt water over the floor  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


One of my wishes is that those dark trees, 

So old and firm they scarcely show the breeze, 

Were not, as 'twere, the merest mask of gloom, 

But stretched away unto the edge of doom. 

I should not be withheld but that some day 



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  

Shining with all his might: 

He did his very best to make 

The billows smooth and bright 

And this was odd, because it was 

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

"I think, therefore I am" 

that's all I need to know 

an answer to the puzzle 

that roused me years ago 

I know all I wish to know 

in my many years on earth 

should I die tomorrow, my 

knowledge spells my worth 


"I think"... not to know it all 

but to let the time pass by 

I don't need an answer 

to every question... why? 
